name: Release Package
on: pull_request

jobs:
  release:
    name: Release package
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.14.2
          registry-url: https://npm.pkg.github.com
      - run: git tag v0.0.1
      - run: git push origin v0.0.1
        env:
          GITHUB_TOKEN: ${{ github.token }}

